# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(default='Doc/None/None-doc.pdf', upload_to='Doc/'),
        ),
    ]
