# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_task_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_active',
            new_name='complited',
        ),
    ]
