# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0005_auto_20170911_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complited',
            new_name='completed',
        ),
    ]
